### ISSUE TITLE
vue tutorial fail to start

### ISSUE THREAD

**Issue by gkrnours** [chromaui/learnstorybook.com#650]
Using latest stable node, tutorial for vue fail to start. Attached is the output of `node -v` followed by the first three commands. The `yarn` command fail to install dependencies as the tutorial say it should do.

```
gkr@rocinante:~/work/perso/vue-taskbox/taskbox 
$ node -v
v16.17.1
[1702] ok.

gkr@rocinante:~/work/perso/vue-taskbox 
$ npx degit chromaui/intro-storybook-vue-template taskbox
> cloned chromaui/intro-storybook-vue-template#HEAD to taskbox
[1702] ok.

gkr@rocinante:~/work/perso/vue-taskbox 
$ cd taskbox/
[1703] ok.

gkr@rocinante:~/work/perso/vue-taskbox/taskbox 
$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
[1703] 1
```

Here is attached output from replacing yarn with npm. As can be seen, install and unit:test seems to work but the storybook fail to start and I'm not familiar enough with modern JS development to fix the issues.

```
gkr@rocinante:~/work/perso/vue-taskbox 
$ node -v
v16.17.1
[1706] ok.

gkr@rocinante:~/work/perso/vue-taskbox 
$ npx degit chromaui/intro-storybook-vue-template taskbox
> cloned chromaui/intro-storybook-vue-template#HEAD to taskbox
[1706] ok.

gkr@rocinante:~/work/perso/vue-taskbox 
$ cd taskbox/
[1706] ok.

gkr@rocinante:~/work/perso/vue-taskbox/taskbox 
$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated error-stack-parser@2.1.3: Please upgrade to error-stack-parser >= v2.1.4, see https://github.com/stacktracejs/error-stack-parser/issues/80
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@3.22.8: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 2826 packages, and audited 2827 packages in 2m

288 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
[1708] ok.

gkr@rocinante:~/work/perso/vue-taskbox/taskbox 
$ npm run test:unit

> intro-storybook-vue-template@0.1.0 test:unit
> vue-cli-service test:unit

 PASS  tests/unit/example.spec.js
  HelloWorld.vue
    ✓ renders props.msg when passed (39 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.286 s
Ran all test suites.
[1708] ok.

gkr@rocinante:~/work/perso/vue-taskbox/taskbox 
$ npm run storybook

> intro-storybook-vue-template@0.1.0 storybook
> start-storybook -p 6006

info @storybook/vue3 v6.5.7
info 
info => Loading presets
info => Serving static files from ././public at /
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modules
info => Ignoring cached manager due to change in manager config
<i> [webpack-dev-middleware] wait until bundle finished
99% done plugins webpack-hot-middlewarewebpack built preview 36cd5fb37a4254abaa12 in 9410ms
assets by chunk 6.29 MiB (id hint: vendors)
  assets by status 5.87 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_manager_js-node_modules_storybook_addon-backgrou-076004.manager.bundle.js 4.79 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_formatter-9bb0ae57_js.manager.bundle.js 813 KiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_OverlayScrollbars-9b821cbe_js.manager.bundle.js 295 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter-b09267a2_js.manager.bundle.js 206 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_WithTooltip-2fc4c925_js.manager.bundle.js 126 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_Color-01c31ae2_js.manager.bundle.js 83.1 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_GlobalScrollAreaStyles-8793ce4a_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.7 KiB [emitted] (name: runtime~main)
asset index.html 3.59 KiB [emitted]
asset main.manager.bundle.js 1.59 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.32 KiB [emitted]
Entrypoint main [big] 4.81 MiB = runtime~main.manager.bundle.js 14.7 KiB vendors-node_modules_storybook_addon-actions_manager_js-node_modules_storybook_addon-backgrou-076004.manager.bundle.js 4.79 MiB main.manager.bundle.js 1.59 KiB
orphan modules 1.02 MiB [orphan] 139 modules
runtime modules 9.09 KiB 15 modules
javascript modules 5.57 MiB 929 modules
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.74.0) compiled successfully in 9392 ms
WARN Force closed manager build
ModuleNotFoundError: Module not found: Error: Can't resolve '@mdx-js/react' in '/home/gkr/work/perso/vue-taskbox/taskbox/src/stories'
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@mdx-js/react' in '/home/gkr/work/perso/vue-taskbox/taskbox/src/stories'
  Parsed request is a module
  using description file: /home/gkr/work/perso/vue-taskbox/taskbox/package.json (relative path: ./src/stories)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/gkr/work/perso/vue-taskbox/taskbox/src/stories/node_modules doesn't exist or is not a directory
      /home/gkr/work/perso/vue-taskbox/taskbox/src/node_modules doesn't exist or is not a directory
      looking for modules in /home/gkr/work/perso/vue-taskbox/taskbox/node_modules
        single file module
          using description file: /home/gkr/work/perso/vue-taskbox/taskbox/package.json (relative path: ./node_modules/@mdx-js/react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.cjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react.vue doesn't exist
        /home/gkr/work/perso/vue-taskbox/taskbox/node_modules/@mdx-js/react doesn't exist
      /home/gkr/work/perso/vue-taskbox/node_modules doesn't exist or is not a directory
      /home/gkr/work/perso/node_modules doesn't exist or is not a directory
      /home/gkr/work/node_modules doesn't exist or is not a directory
      /home/gkr/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
99% done plugins webpack-hot-middlewarewebpack built preview fe22c28bbe995bac4d33 in 279ms
✔ Would you like to send crash reports to Storybook? … yes

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

[1709] 1
```

**Comment by jonniebigodes** [comment]
@gkrnours, sorry for the delay in following back on your issue. It's been a couple of busy weeks around here and I've been tasked with other documentation issues.

I've ran the steps in the tutorial and wasn't able to reproduce this. I used the following testing approach:
- Mac node v16.17.1 
- Mac node v16.13.2
- Windows v16.13.2
- Windows v16.17.1 
- Ubuntu 20.04 LTS (WSL) node v16.17.1
- Ubuntu 20.04 LTS (WSL) node v16.13.2

And all checked out ok. But that doesn't mean there isn't an issue, and I'll need more clarification before proceeding. The first thing that grabbed my attention was:
 > $ npx degit chromaui/intro-storybook-vue-template taskbox
> cloned chromaui/intro-storybook-vue-template#HEAD to taskbox

When running the command in the environments, I've mentioned, they all returned the following:
> ❯ npx degit chromaui/intro-storybook-vue-template taskbox
> cloned chromaui/intro-storybook-vue-template#master to taskbox-

Why it's fetching `#HEAD` as opposed to the master branch is something that shouldn't be happening. Also, if you're willing, can you provide me with the `yarn` version you're using if memory serves me right, that issue is actually a `yarn` issue, not a Storybook one. The one that's a Storybook issue is the `ModuleNotFoundError: Module not found: Error: Can't resolve '@mdx-js/react'`. Various users have already encountered it as well, as you can see [here](https://github.com/storybookjs/storybook/issues/18599) and [here](https://github.com/storybookjs/storybook/issues/18094). 

Can you do me a favor and check if the workarounds mentioned in the issues solve your issue?

Looking forward to hearing from you.

Hope you have a great weekend.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this for now, let me know if you're still experiencing the issue and I'll gladly follow-up with you on this.

Hope you have a fantastic weekend.

Stay safe
